
  create table "public"."crops" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "description" text,
    "size" real,
    "start_date" date,
    "end_date" date,
    "user" uuid
      );


alter table "public"."crops" enable row level security;


  create table "public"."expenses" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "description" text,
    "expense_type" bigint,
    "amount" double precision,
    "crop_id" smallint
      );


alter table "public"."expenses" enable row level security;


  create table "public"."expenses_type" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "description" text not null
      );


alter table "public"."expenses_type" enable row level security;

alter table "public"."users" add column "email" text;

CREATE UNIQUE INDEX crops_pkey ON public.crops USING btree (id);

CREATE UNIQUE INDEX expenses_pkey ON public.expenses USING btree (id);

CREATE UNIQUE INDEX expenses_type_pkey ON public.expenses_type USING btree (id);

alter table "public"."crops" add constraint "crops_pkey" PRIMARY KEY using index "crops_pkey";

alter table "public"."expenses" add constraint "expenses_pkey" PRIMARY KEY using index "expenses_pkey";

alter table "public"."expenses_type" add constraint "expenses_type_pkey" PRIMARY KEY using index "expenses_type_pkey";

alter table "public"."crops" add constraint "crops_user_fkey" FOREIGN KEY ("user") REFERENCES public.users(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."crops" validate constraint "crops_user_fkey";

alter table "public"."expenses" add constraint "expenses_crop_id_fkey" FOREIGN KEY (crop_id) REFERENCES public.crops(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."expenses" validate constraint "expenses_crop_id_fkey";

alter table "public"."expenses" add constraint "expenses_expense_type_fkey" FOREIGN KEY (expense_type) REFERENCES public.expenses_type(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."expenses" validate constraint "expenses_expense_type_fkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.is_active_admin()
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select exists (
    select 1
    from public.admin_profiles ap
    where ap.id = auth.uid()
      and ap.is_active = true
  );
$function$
;

CREATE OR REPLACE FUNCTION public.set_updated_at()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
begin
  new.updated_at = now();
  return new;
end;
$function$
;

grant references on table "public"."crops" to "anon";

grant trigger on table "public"."crops" to "anon";

grant truncate on table "public"."crops" to "anon";

grant references on table "public"."crops" to "authenticated";

grant trigger on table "public"."crops" to "authenticated";

grant truncate on table "public"."crops" to "authenticated";

grant delete on table "public"."crops" to "service_role";

grant insert on table "public"."crops" to "service_role";

grant references on table "public"."crops" to "service_role";

grant select on table "public"."crops" to "service_role";

grant trigger on table "public"."crops" to "service_role";

grant truncate on table "public"."crops" to "service_role";

grant update on table "public"."crops" to "service_role";

grant references on table "public"."expenses" to "anon";

grant trigger on table "public"."expenses" to "anon";

grant truncate on table "public"."expenses" to "anon";

grant references on table "public"."expenses" to "authenticated";

grant trigger on table "public"."expenses" to "authenticated";

grant truncate on table "public"."expenses" to "authenticated";

grant delete on table "public"."expenses" to "service_role";

grant insert on table "public"."expenses" to "service_role";

grant references on table "public"."expenses" to "service_role";

grant select on table "public"."expenses" to "service_role";

grant trigger on table "public"."expenses" to "service_role";

grant truncate on table "public"."expenses" to "service_role";

grant update on table "public"."expenses" to "service_role";

grant delete on table "public"."expenses_type" to "anon";

grant insert on table "public"."expenses_type" to "anon";

grant references on table "public"."expenses_type" to "anon";

grant select on table "public"."expenses_type" to "anon";

grant trigger on table "public"."expenses_type" to "anon";

grant truncate on table "public"."expenses_type" to "anon";

grant update on table "public"."expenses_type" to "anon";

grant delete on table "public"."expenses_type" to "authenticated";

grant insert on table "public"."expenses_type" to "authenticated";

grant references on table "public"."expenses_type" to "authenticated";

grant select on table "public"."expenses_type" to "authenticated";

grant trigger on table "public"."expenses_type" to "authenticated";

grant truncate on table "public"."expenses_type" to "authenticated";

grant update on table "public"."expenses_type" to "authenticated";

grant delete on table "public"."expenses_type" to "service_role";

grant insert on table "public"."expenses_type" to "service_role";

grant references on table "public"."expenses_type" to "service_role";

grant select on table "public"."expenses_type" to "service_role";

grant trigger on table "public"."expenses_type" to "service_role";

grant truncate on table "public"."expenses_type" to "service_role";

grant update on table "public"."expenses_type" to "service_role";


